// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path"; // Importa o módulo 'path' para manipulação de caminhos de arquivos
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // schema: "prisma/schema.prisma",
  schema: path.join("prisma", "schema.prisma"),
  migrations: {
    path: path.join("prisma", "migrations"),
    // path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
