// src/lib/rbac/types.ts
export type Role = "SERVIDOR" | "GESTOR" | "ADMIN" | "MASTER";

export type Permission =
  | "DASHBOARD_VIEW"
  | "PONTO_ESPELHO_VIEW"
  | "PONTO_REGISTROS_VIEW"
  | "PONTO_OCORRENCIAS_VIEW"
  | "PONTO_SOLICITACOES_CREATE"
  | "PONTO_SOLICITACOES_APPROVE"
  | "RELATORIOS_VIEW"
  | "RELATORIOS_EXPORT"
  | "FUNCIONARIO_VIEW"
  | "FUNCIONARIO_CREATE"
  | "FUNCIONARIO_EDIT"
  | "FUNCIONARIO_IMPORT_SARH"
  | "RELOGIO_VIEW"
  | "RELOGIO_CREATE"
  | "RELOGIO_EDIT"
  | "AFD_IMPORT"
  | "AFD_PROCESS"
  | "ESCALAS_VIEW"
  | "ESCALAS_EDIT"
  | "EQUIPE_VIEW"
  | "EQUIPE_MANAGE"
  | "AUDITORIA_VIEW"
  | "PARAMETROS_EDIT"
  | "PERMISSOES_MANAGE"
  | "TENANT_SWITCH";
